stages:
  - build
  - test

create_file:
  image: alpine
  stage: build
  script:
    - echo "building ..."
    - mkdir build
    - touch build/somefile.txt
  artifacts:
    paths:
      - build/

test_file:
  image: alpine
  stage: test
  script:
    - test -f build/somefile.txt
